version: "3"
services:
  spotify-obs:
    ports:
      - <PORT>:8888
    container_name: spotify-obs
    restart: unless-stopped
    environment:
      - CLIENT_ID=<CLIENT_ID>
      - CLIENT_SECRET=<CLIENT_SECRET>
      - HOST=<HOST>
      - PORT=<PORT>
    image:
      d3vle0/spotify-obs